### ISSUE TITLE
Cannot run cmake

### ISSUE THREAD

**Issue by aaronenyeshi** [ROCmSoftwarePlatform/rocPRIM#19]
I'm trying to run cmake on rocPRIM develop branch, and I encounter this issue:
```
[ 22%] Performing configure step for 'googlebenchmark-download'
CMake Error at /root/rocPRIM/build/googlebenchmark-download/googlebenchmark-download-prefix/src/googlebenchmark-download-stamp/googlebenchmark-download-configure-.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-DCMAKE_BUILD_TYPE=RELEASE' '-DBENCHMARK_ENABLE_TESTING=OFF' '-DBUILD_SHARED_LIBS=ON' '-DCMAKE_INSTALL_PREFIX=/root/rocPRIM/build/googlebenchmark' '-GUnix Makefiles' '/root/rocPRIM/build/googlebenchmark-src'

  See also

    /root/rocPRIM/build/googlebenchmark-download/googlebenchmark-download-prefix/src/googlebenchmark-download-stamp/googlebenchmark-download-configure-*.log


CMakeFiles/googlebenchmark-download.dir/build.make:101: recipe for target 'googlebenchmark-download-prefix/src/googlebenchmark-download-stamp/googlebenchmark-download-configure' failed
make[2]: *** [googlebenchmark-download-prefix/src/googlebenchmark-download-stamp/googlebenchmark-download-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/googlebenchmark-download.dir/all' failed
make[1]: *** [CMakeFiles/googlebenchmark-download.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at cmake/DownloadProject.cmake:168 (message):
  Build step for googlebenchmark failed: 2
Call Stack (most recent call first):
  cmake/Dependencies.cmake:102 (download_project)
  CMakeLists.txt:63 (include)


-- Configuring incomplete, errors occurred!
See also "/root/rocPRIM/build/CMakeFiles/CMakeOutput.log".
```
Is this due to some other issue with downloading google benchmark?

**Comment by ex-rzr** [comment]
> Is this due to some other issue with downloading google benchmark?

Perhaps. Could you show `/root/rocPRIM/build/googlebenchmark-download/googlebenchmark-download-prefix/src/googlebenchmark-download-stamp/googlebenchmark-download-configure-*.log
`? I hope there are more details.

Is this the first time you've encountered this issue on this system? It's possible that something changed on your system.

There are no changes in `rocPRIM/cmake/Dependencies.cmake` during the last 3 months. And we download Google Benchmark by the tag, not the latest master, so it can't be due to some changes in the Google Benchmark repository.

But just to be sure please try to build the master branch.

**Comment by jszuppe** [comment]
You can also comment out lines [108; 111] in [cmake/Dependencies.cmake](https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/develop/cmake/Dependencies.cmake#L108) to see the log in console.

**Comment by aaronenyeshi** [comment]
Oh strangely, I tried it again today, and it didn't have the same error. Maybe it was some connection issue
