### ISSUE TITLE
is the benchmark results time correct? 

### ISSUE THREAD

**Issue by xqch1983** [ROCmSoftwarePlatform/rocPRIM#34]
is the benchmark results time correct? 
one radix-sort item for example:
sort_pairs<int, float>/iterations:1/manual_time     12 ms          1 ms          1   6.73374GB/s   861.919M items/s
if items_per_second = 8.16E+08,
Baidu need items of 1E+06, so it can finish 810 times per second.
1/810 = 0.001234second = 1.234 ms 
maybe the 1.2ms in console out is right?

**Comment by ex-rzr** [comment]
In benchmarks we usually run a few iterations (`batch_size = 10`) to make benchmarks more stable:

https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/master/benchmark/benchmark_hip_device_radix_sort.cpp#L127

So `Time` is indeed 10x bigger. Google Benchmark is confused by `state.SetIterationTime(elapsed_seconds.count() / batch_size)` and runs benchmarks longer than required. So you may simply divide Time by 10 or use `batch_size = 1`.

And don't forget to specify `--size` command line argument if you need to check performance for 1M items (instead of default 32M), because Radix sort works faster (items/s) for large sizes, i.e. 1M will have lower items/s than 32M.

**Comment by xqch1983** [comment]
thanks for you reply immdiately, can you share one shell script to build one case to use our sort api, for exmape hip-radix-sort,especially the link and include files to include and link, thanks.

I copy some codes form benchmark_hip_xxx.cpp, but always faild in comile and link states.

**Comment by VincentSC** [comment]
Did you manage? If not, please share the compilation errors when copying code from the benchmark-sources.

**Comment by xqch1983** [comment]
Yes, I have do it, thanks very much.
